# Generated by Django 3.1 on 2022-02-17 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TasksTopo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bk_biz_id', models.IntegerField(verbose_name='业务id')),
                ('bk_obj_id', models.CharField(max_length=50, verbose_name='拓扑类型')),
                ('bk_inst_id', models.IntegerField(verbose_name='集群id')),
                ('bk_inst_name', models.CharField(max_length=255, verbose_name='节点名称')),
                ('path', models.TextField(verbose_name='拓扑路径')),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.IntegerField(verbose_name='任务名称')),
                ('test_list', models.JSONField()),
                ('test_char', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_topo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tasks', to='model_serializer.taskstopo')),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=32, verbose_name='任务名称，与报告名称相同')),
                ('task_type', models.CharField(max_length=32, verbose_name='任务类型')),
                ('name', models.CharField(max_length=32, verbose_name='报告名称')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_id', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='report', to='model_serializer.tasks')),
            ],
        ),
    ]
